const sentenses = [
  'Detroit is famous for the ....... of cars.',
  'If you make a good ....... at the interview, you will get the job.',
  "Teaching and medicine are more than ......., they're professions.",
  'My history teacher has a good ....... of past events.',
  'You are never too old to go to college and gain some .......',
  'My greatest ....... was graduating from the university.',
  'The weatherman said there is a strong ....... of rain today.',
  'Some old laws are no longer .......',
  'Athens is ....... for its ancient buildings.',
  'He was caught shoplifting so now he has a ....... record.',
  'Despite her severe ......., she fulfilled her goals in life.',
  'Being ....... is the worst thing that can happen to someone.',
  'If you buy presents in the summer your ....... can be very high.',
  "Due to the pilot's ....... the copilot managed to land safely.",
  "It's important to also see the less ....... sides of the job.",
  'The leader of the Queen - Farrokh Bulsara - is more ....... known as Freddie Mercury.',
  'The most ....... thing about travelling is meeting new people.',
  'It is ....... to sell cigarettes to people under 16.',
  'She is a very ....... driver, she’s never had an accident.',
  'Our grandfather was ......., so he went to sleep.',
  'The .....master at my school was very strict.',
  'Write your name and address on the card, and put it in the .....box.',
  'The last scene in Titanic is .....-breaking.',
  'I want decaffeinated sugar-..... cappuccino.',
  'I have to go to work this evening, can you baby..... with my son?',
  'Her husband bought her gorgeous ear.....',
  'He always gets up before sun.....',
  'Put on your .....shirt if it is cold.',
  'We have so many books, we need a new book.....',
  'I took a pill, but I still have that terrible stomach.....',
  'Before starting a project, brain..... your ideas with the colleagues.',
  'It’s better to eat Chinese food with chop.....',
  'If you want to listen to high quality music, buy expensive ear.....',
  'The computer comes with a wireless mouse and .....board.',
  'Back..... are great for hiking and camping.',
  'When I was a student, I had a .....-time job as a waiter.',
  'The school has students from many different cultural back.....',
  "Canvas boots are all right, but they're not as .....proof as leather.",
  "You'll need some tough foot..... to go hiking in the mountains.",
  'Success in this competitive field will depend on good team.....',
  'We did some sight.....in Paris.',
  'I can’t go ..... tonight, because I have to study for my exam.',
  'I’d like to take..... flamenco dancing, but I’m afraid I’m too stiff to do it.',
  'I’ve been looking ..... my pen for an hour but I can’t find it anywhere.',
  'She took ..... her cardigan as it was incredibly hot.',
  'Can you look ..... the kids tomorrow afternoon? I have a job interview.',
  'I don’t get ..... that well with my sister, we always fight.',
  "She found ..... that he'd been cheating on her.",
  'Joan grew ..... in Hong Kong.',
  'She gave ..... smoking when she discovered she was pregnant.',
  'Keep ..... trying and you’ll succeed in the end.',
  'The television isn’t working because it isn’t plugged .....',
  'I want to ..... this blouse on before buying.',
  'The plane ..... off four hours late.',
  'This jacket ..... with my new trousers.',
  'Sam and Lisa ..... up last month.',
  'The children were all ..... forward to the party.',
  'Don’t ..... away the newspaper, I haven’t read it yet.',
  'If you don’t like the shoes, we can ..... them back to the shop.',
  '..... out! There’s a car coming!',
  '..... off the lights when you leave.',
  "She's at that age where she's starting to get interested .....boys.",
  "She's keen ..... playing tennis.",
  "Don't waste your money ..... such junk.",
  'I was never any good ..... art.',
  'Who doesn’t like listening ..... music?',
  'The film is based ..... the novel by Boris Pasternak.',
  'I suffer ..... hay fever.',
  'If you make so much noise, I can’t concentrate ..... my work.',
  'This shampoo smells ..... bananas.',
  'After the main course, he asked ..... dessert.',
  "Hotel management is hard work, but it's not rocket .....",
  "I'm just going to cross my ..... and hope it works.",
  "I'm all ..... - tell us what they’ve said.",
  'She was as busy as a ..... the whole day.',
  'She’s so hungry she could eat a .....',
  'She followed in her mother’s ..... and started her own business.',
  'The weather is awful, it’s raining cats and .....',
  'A couch ..... likes to spend time at home, watching TV.',
  'My father was a ..... in sheep’s clothing – he looked like a sweet man, but he was really bad.',
  'Thank you for your suggestion – it gave us a lot of ..... for thought.',
  'He ..... me about his life in Germany.',
  'My youngest child is ..... to ride a bike.',
  'He ..... some noise from the street.',
  'She ..... at the book cover and saw that it was old.',
  'He was ..... me as I entered the building.',
  'The newspaper guy ..... the newspaper to my house every morning.',
  'I got a job ..... from a pretty big company.',
  'I had a terrible ..... to work this morning.',
  'Do you want to ..... snowboarding this weekend?',
  'Tim was fine, but his car was ..... in the accident.',
  'Make sure you are given a ..... for everything you buy.',
  "Some people's teeth are highly ..... to cold.",
  'It was most generous of you to ..... me the money.',
  'It looks like we are going to have a beautiful ..... day today.',
  'I like my home because there is a lot of ..... for all my things.',
  'I was too ..... to admit that I was scared.',
  'My father told me a ..... of how he met my mother.',
  'I have a good job and a family - I don’t want to change anything in my .....',
  'I don’t know ..... who doesn’t like pizza.',
];

export default sentenses;
